platform :ios, '9.0'
inhibit_all_warnings!

target 'HarvardArtMuseum' do
  use_frameworks!
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'PromiseKit'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'SwinjectAutoregistration'
  pod 'AlamofireImage'
end